---
- name: Test deploy
  hosts: ubuntu-home
  become: yes

  tasks:

  - name: Create user deployer
    user:
      name: deployer
      groups: sudo
      password: 'SecretPassword'
      shell: /bin/bash
      update_password: on_create

  - name: Add ssh_key
    authorized_key: user=deployer key="{{ lookup('file', "/mnt/c/Users/kille/Documents/job/KeyForTests.pub") }}"

  - name: Don't ask for pass
    copy:
      src: deployer
      dest: /etc/sudoers.d/deployer

  - name: Install redis-server
    apt:
      name: redis-server
      state: latest
  
  - name: Install python3-pip
    apt:
      name: python3-pip
      state: latest

  - name: Install python3-venv
    apt:
      name: python3-venv
      state: latest

  - name: Install mariadb
    apt:
      name: mariadb-server
      state: latest

  - name: Install PyMySQL via pip (for create database)
    pip:
      name: PyMySQL==0.7.11
      executable: pip3

  - name: Copy initial MySQL client config file, no password, for root
    copy:
      src: .my.cnf
      dest: /root/.my.cnf

  - name: Create the MySQL databases tickers and tickers_test
    mysql_db:
      name:
      - "tickers_test"
      - "tickers"
      state: present

  - name: Create database user
    mysql_user:
      name: tickers
      password: "tickers"
      priv: 'tickers.*:ALL/tickers_test.*:ALL'
      state: present

  - name: Clone git
    git:
      repo: https://github.com/Ageres210784/tickers.git
      dest: /home/deployer/tickers
#    become_user: deployer

  - name: Pip - install requirements using shell
    shell: |
      cd /home/deployer/tickers
      python3 -m venv venv
      . venv/bin/activate
      pip install -r requirements.txt
      deactivate
      chown -R deployer: ./

  - name: Copy services gunicorn and celery
    shell: |
      cp /home/deployer/tickers/extra/systemd/gunicorn.service /etc/systemd/system
      cp /home/deployer/tickers/extra/systemd/celery.service /etc/systemd/system
      cp /home/deployer/tickers/extra/systemd/celeryd /etc/default

  - name: Create dir /var/run/celery
    file:
      path: /var/run/celery
      state: directory
      owner: deployer
      group: deployer

  - name: Create dir /var/log/celery
    file:
      path: /var/log/celery
      state: directory
      owner: deployer
      group: deployer

  - name: Start service gunicorn
    systemd:
      name: gunicorn
      state: started
      enabled: yes
      daemon_reload: yes

  - name: Start service celery
    systemd:
      name: celery
      state: started
      enabled: yes
      daemon_reload: yes
