---
- name: Converge
  hosts: all

  vars:
    mariadb_root_password: "{{ lookup('password', '/tmp/mariadb_root_password length=15 chars=ascii_letters,digits,hexdigits') }}"

    mariadb_users:
      - name: example
        password: "{{ lookup('password', '/tmp/mariadb_example_password length=15 chars=ascii_letters,digits,hexdigits') }}"
        priv: "example.*:ALL"
        state: present

    mariadb_databases:
      - name: example
        state: present

  roles:
    - role: cloudweeb.mariadb
