---

- name: MySQL secure install | Disallow root login remotely
  command: >
    mysql -NBe "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"
  changed_when: false

- name: Get list of hosts for the root user.
  command: mysql -NBe
    "SELECT Host
    FROM mysql.user
    WHERE User = 'root'
    ORDER BY (Host='localhost') ASC"
  register: mysql_root_hosts
  changed_when: false
  check_mode: false

- name: Check if .my.cnf exists
  become: yes
  become_user: root
  stat:
    path: "~/.my.cnf"
  register: mycnf

- name: Get password from .my.cnf
  become: yes
  become_user: root
  shell:
    cmd: |
      grep password ~/.my.cnf | cut -d= -f2 | tr -d '"'
  register: mycnf_current_password
  changed_when: false
  when: mycnf.stat.exists

# Note: We do not use mysql_user for this operation, as it doesn't always update
# the root password correctly. See: https://goo.gl/MSOejW
# Set root password for MySQL >= 5.7.x.
- name: Update MySQL root password for localhost root account (5.7.x+).
  become: yes
  become_user: root
  shell:
    cmd: |
      mysql -u root -NBe 'SET old_passwords=0; ALTER USER "root"@"{{ item }}" IDENTIFIED BY "{{ mariadb_root_password }}";'
  with_items: "{{ mysql_root_hosts.stdout_lines|default([]) }}"
  when: (mycnf_current_password.stdout is defined and mycnf_current_password.stdout != mariadb_root_password) or mycnf_current_password.stdout is not defined

- name: Set my.cnf file with root password credentials
  become: yes
  become_user: root
  copy:
    content: |
      [client]
      user="root"
      password="{{ mariadb_root_password }}"
    dest: ~/.my.cnf
    mode: 0600
  no_log: true

- name: MySQL secure install | Remove anonymous users
  become: yes
  become_user: root
  mysql_user:
    name: ''
    host_all: true
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL secure install | Remove test database
  become: yes
  become_user: root
  mysql_db:
    name: test
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock
