---

- name: Manage database users
  become: yes
  become_user: root
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    host: "{{ item.host | default('localhost') }}"
    priv: "{{ item.priv | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    login_unix_socket: /run/mysqld/mysqld.sock
  loop: "{{ mariadb_users }}"
  no_log: true
